name: Build Cyclone API Library

on:
push:
branches:
  - master
pull_request:

jobs:
build:
runs-on: ubuntu-latest
strategy:
matrix:
node: [12, 14]
steps:
- name: Compile Typescript
  run: npm run build